apiVersion: v1
kind: Service
metadata:
  name: kst-model-app
  labels:
    app: kst-model-app
spec:
  selector:
    app: kst-model-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
      name: http
  type: ClusterIP
